name: check
on:
  pull_request:
    branches:
      - main
jobs:
  build:
  runs-on: ubuntu-latest

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v25

    - name: Build Nix derivation
      run: |
        nix build .#default
        echo "site output is in result/"

    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./result
